#! /bin/sh

sxhkd &

# CUSTOM
# picom &

pkill polybar
nitrogen --set-scaled /usr/share/backgrounds/mass_effect.png

~/.config/polybar/launch.sh
# CUSTOM ENDS

bspc monitor -d 1 2 3 4 5 6 7 8 9

# bspc config automatic_scheme spiral
# bspc config automatic_scheme first_child
# bspc config automatic_scheme longest_side
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   0
bspc config bottom_padding                10
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"


# Find class name by using
# xprop | grep WM_CLASS
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox-esr desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
